Lesson 6
DaniyarKulmanov/TestGuru- pull request #5
Opened 2021-04-27 09:47 UTC by DaniyarKulmanov

2021-04-27 16:34 UTC, VidgarVii requested changes

2021-04-27 16:34 UTC, VidgarVii commented on app/models/answer.rb
> +  validates :correct, presence: true
нет валидации для 
Наличие атрибутов title, body, email в соответствующих моделях

2021-04-27 16:34 UTC, VidgarVii commented on app/models/question.rb
> +  end
не очень понятно как валидация в модели Вопрос будет препятствовать созданию новых ответов в количестве больше 4... она же не будет вызываться, когда ты будешь добавлять новые ответы к вопросу - вызываются валидации того класса, объекты которого создаются

при создании нового объекта класса Ответ вызываются валидации класса Ответ, а не класса Вопрос

видимо ты не проверяла работу этой валидации

2021-04-27 16:34 UTC, VidgarVii commented on app/models/test.rb
> +  INFINITE = Float::INFINITY
у тебя тут константа для константы

2021-04-27 16:34 UTC, VidgarVii commented on app/models/test.rb
> +  }
у скоупов есть важная особенность - они должны возвращать chainable объекты (объекты `ActiveRecord::Relation`)
благодаря этому с их использованием можно строить цепочки вызовов
скоупы можно чейнить с квери-методами  `ActiveRecord`, к примеру `where(level: ...).order(id: :desc).created_last_week ...`, с методами ассоциаций
квери-методы также возвращают объекты `ActiveRecord::Relation`
НО!
`pluck` вернет обычный массив, что нарушит эту конвенцию
поэтому, если скоуп должен вернуть объект или массив, но не `ActiveRecord::Relation`, то его лучше реализовывать обычными методами класса

здесь можно создать скоуп, который будет делать, к примеру, все кроме `pluck`
а при желании сохранить прежнюю функциональность можно оставить плюс к скоупу метод класса и уже в методе класса (из прошлого задания) убрать все запросы, вызвать этот скоуп и зачейнить его "плаком"

2021-04-27 16:34 UTC, VidgarVii commented on app/models/user.rb
> +  validates :name, presence: true
нет валидации почты

2021-04-28 15:17 UTC, VidgarVii requested changes

2021-04-28 15:17 UTC, VidgarVii commented on app/models/answer.rb
> +  scope :proper, -> { where(correct: true) }
scope пишут после валидаций (исключение default scope)

2021-04-28 15:17 UTC, VidgarVii commented on app/models/answer.rb
> +  validates :correct, inclusion: { in: [true, false] }
данная проверка должна быть на уровне БД в миграции
1 должно быть булевое поле
2 исключить null

2021-04-28 15:17 UTC, VidgarVii commented on app/models/answer.rb
> +  validate :validate_answers_count, if: :question_exist?
question_exist? проверяется на уровне объявления ассоциации в belongs_to
Т.е. belongs_to (без атрибута optioanal) уже проверяет обязательное наличие вопроса. 

тут нужна опция, чтобы данный валидатор работал только при создании вопроса.
Смотри документацию для опции :on

2021-04-28 15:17 UTC, VidgarVii commented on app/models/answer.rb
> +    puts (1..4).include?(question.answers.size)
путс тут очень грязный side effect. Так же в нём нет смысла.

2021-04-28 15:17 UTC, VidgarVii commented on app/models/answer.rb
> +    errors.add(:question, 'only 1 - 4 question allowed') unless (1..4).include?(question.answers.size)
я бы скорее рекомендовал использовать в подобных валидациях `count` и проверку тогда надо записать `question.answers.count >= 4`
нас интересуют именно хранящиеся в базе ответы, точнее их количество
`size` же при наличии объектов в памяти берет их из памяти (а при отсутствии подгружает из базы)

в данном простом случае думаю оба варианта будут вести себя корректно, но в случае более сложной логики можно с `size` получить неожиданные ошибки
в памяти же может быть уже "перебор" и объект не создастся, при этом в базе еще "недобор"

по поводу методов подсчета объектов `count`, `size`, `length` - посмотри для самообразования [вот этот вопрос на СО](https://stackoverflow.com/questions/6083219/activerecord-size-vs-count) и конечно же ответы к нему
1-ый и 2-ой ответы довольно лаконично и понятно объясняют что делают методы

Данный код мб и работает корректно, но ооочень мутный и не явный. Мы не знаем что именно сейчас в памяти

2021-04-28 15:17 UTC, VidgarVii commented on app/models/answer.rb
> +  end
.present?

2021-04-28 15:17 UTC, VidgarVii commented on app/models/test.rb
> +  }
если блок занимает больше 1 строки, тогда используют do end
Вообще многострочные скоупы не очень хорошая пркатика. Стайл лайгд советует в таких ситуациях придерживаться методами класса

2021-04-28 15:17 UTC, VidgarVii commented on app/models/test.rb
> +  scope :by_category, lambda { |category|
->

2021-04-28 15:17 UTC, VidgarVii commented on config/initializers/version.rb
> +    VERSION = '0.1.6'
куда фриз пропал?

2021-04-28 15:17 UTC, VidgarVii commented on config/locales/ru.yml
> +              invalid: 'Не верный формат электронной почты'
пустую строку надо оставлять

2021-04-29 08:02 UTC, DaniyarKulmanov commented on config/initializers/version.rb
> +    VERSION = '0.1.6'
Рубокоп ругается что не надо фризить литералы и убирает + есть строчка вверху # frozen_string_literal: true
она выполняет это? ?

2021-04-29 18:41 UTC, VidgarVii requested changes

2021-04-29 18:41 UTC, VidgarVii commented on app/models/answer.rb
> +  validates :correct, inclusion: { in: [true, false] }
не исправил

2021-04-29 18:41 UTC, VidgarVii commented on app/models/question.rb
> +  end
Тут корректно проверять наличие ответов в БД. Только база может быть источником правды. А в памяти может твориться полный хаос.
У вопроса вообще может не быть ответов. И это нормально! Например после создания вопроса. И данный код сбивает с толку. Почему должен быть 1 ответ?

2021-04-30 15:27 UTC, VidgarVii requested changes

2021-04-30 15:27 UTC, VidgarVii commented on app/models/answer.rb
> +  scope :proper, -> { where(correct: true) }
для данного кейса более подходящее название скоупу это просто повторить название поле
```
scope :correct, -> { where(correct: true) }
```

2021-04-30 15:27 UTC, VidgarVii commented on app/models/question.rb
> +  end
не исправил

2021-05-05 15:42 UTC, VidgarVii commented on app/models/question.rb
> +    errors.add(:question, 'maximum 4 answers allowed') if answers.count > 4
позволит записать в БД 5 ответов

2021-05-05 15:42 UTC, VidgarVii commented on app/models/test.rb
> +    by_category(category).pluck(:title)
можно было оставить 1 метод класса

2021-05-11 05:21 UTC, merged